### ISSUE TITLE
Mojo doc reference needs to be updated

### ISSUE THREAD

**Issue by dbaker-rh** [openshift/elliott#164]
Mojo reference in https://github.com/openshift/elliott/blob/master/README.md

The page you tried to load was originally found on Mojo, but it was contained in an area marked as not needed in The Source.
It will not be migrated.

**Comment by sosiouxme** [comment]
Thanks.
https://github.com/openshift/elliott/commit/0cbadf80604b530ed1f5fb20a5bc9cedc98b1998
