### ISSUE TITLE
Some spots for better error checking

### ISSUE THREAD

**Issue by tbielawa** [openshift/elliott#38]
Hi @smunilla, long time user here -- I love your product! I'm writing today to point out two areas I think we could improve error checking and reporting.

1. Bugzilla isn't logged in. It'd be nice if we could notice when a bugzilla call gives the unauthorized error

```
xmlrpclib.Fault: <Fault 102: 'You are not authorized to access bug #1605844. To see this bug, you must first log in to an account with the appropriate permissions.'>
```

2. This weird connection reset error could be caught and retried I think:

```
requests.exceptions.ChunkedEncodingError: ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))
```

Both of these happened while running:

```
./elliott --group=openshift-4.1 repair-bugs --noop --use-default-advisory rpm --auto
```

**Comment by thiagoalessio** [comment]
@tbielawa please let me know if this is still relevant. If so, let's create a JIRA and close this issue ;D

**Comment by shiywang** [comment]
@tbielawa same here, can we close this?

**Comment by thiagoalessio** [comment]
ok, closing this in order to show some triage work :rofl: we can follow up with a JIRA if needed.
