### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by yazug** [openshift/elliott#84]
In starting to look at elliott I noticed a number of possible issues with python3 support in the code base.  Below are a few that I saw so far.

- tox missing py3 target (available in the python-3 branch)
- setup.py is missing test deps
- print() issue
- urlparse error
- unicode
- absolute vs relative imports
- iteritems
- dict values() is view not a list in python3
- contextlib.next was replace by ExitStack  (in a unittest)
- unittests and elliottlib.assertions.FileNotFoundError and ChildProcessError are not working in py3

I did see pull request #82 started looking at this

**Comment by yazug** [comment]
Looks like there is topic branch of python-3 with some work

**Comment by vfreex** [comment]
Fixed by #85 and #104.
