### ISSUE TITLE
Fix dev container kinit failed

### ISSUE THREAD

**Issue by shiywang** [openshift/elliott#97]
```
[dev@dbaf7d0152d0 elliott]$ kinit shiywang
kinit: Invalid UID in persistent keyring name while getting default ccache
```

**Comment by vfreex** [comment]
@shiywang I can't reproduce with the latest version. Can you check if https://github.com/openshift/elliott/pull/95 fix this?

**Comment by vfreex** [comment]
This is fixed by https://github.com/openshift/elliott/pull/95
