### ISSUE TITLE
Be able to specify customized user instead of hardcoded "dev"

### ISSUE THREAD

**Issue by shiywang** [openshift/elliott#98]
Once VScode support this https://github.com/microsoft/vscode-remote-release/issues/46
we can use buildArgs to specify our own user like USER=$(id -un) instead of dev.

**Comment by vfreex** [comment]
If you are running dev container with docker on Linux, you just need to make sure that the UID in the container matches your actual UID, while the value of username doesn't matter.

But of cause it would be nice to make the username matches the actual username to avoid confusion.

**Comment by vfreex** [comment]
https://github.com/openshift/elliott/pull/104 switched to use docker-compose.yaml to build images. We can add a build arg there.

**Comment by sosiouxme** [comment]
This happened at some point :)
